# Generated by Django 5.1.4 on 2025-02-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderItem', '0002_alter_orderitemmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
