# Generated by Django 5.1.4 on 2025-02-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderItem', '0003_alter_orderitemmodel_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='total_price',
        ),
    ]
