# Generated by Django 5.1.4 on 2025-02-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderItem', '0005_remove_orderitemmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='discount',
        ),
    ]
