# Generated by Django 5.1.6 on 2025-03-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderItem', '0007_orderitem_delete_orderitemmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='tb_orderitem',
        ),
    ]
