# Generated by Django 5.1.6 on 2025-03-11 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderItem', '0008_alter_orderitem_table'),
        ('product', '0021_remove_product_id_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product'),
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='tb_orderItem',
        ),
    ]
