# Generated by Django 5.1.6 on 2025-04-14 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderItem', '0009_orderitem_product_alter_orderitem_table'),
        ('product', '0022_remove_product_product_id_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product'),
        ),
    ]
