# Generated by Django 5.1.4 on 2025-02-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='tb_cart',
        ),
    ]
