# Generated by Django 5.1.4 on 2025-01-10 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='tb_order',
        ),
    ]
