# Generated by Django 5.1.4 on 2025-02-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartItem', '0002_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
