# Generated by Django 5.1.4 on 2025-02-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartItem', '0003_remove_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
