# Generated by Django 5.1.4 on 2025-02-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartItem', '0004_remove_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price',
        ),
    ]
