# Generated by Django 5.1.4 on 2025-02-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartItem', '0005_remove_cartitem_total_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='tb_cartItem',
        ),
    ]
