# Generated by Django 5.1.4 on 2025-02-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isPromo',
            field=models.BooleanField(default=False),
        ),
    ]
