# Generated by Django 5.1.4 on 2025-02-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_category_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
