# Generated by Django 5.1.4 on 2025-02-12 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='tb_product',
        ),
    ]
