# Generated by Django 5.1.4 on 2025-02-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isPromo',
        ),
    ]
