# Generated by Django 5.1.6 on 2025-03-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_discount_alter_product_old_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='productName',
        ),
    ]
