# Generated by Django 5.1.6 on 2025-03-11 12:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000'), editable=False, primary_key=True, serialize=False),
        ),
    ]
