# Generated by Django 5.1.6 on 2025-03-11 12:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uuid_temp',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
