# Generated by Django 5.1.6 on 2025-03-11 13:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_product_uuid_temp_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uuid_temp',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
