# Generated by Django 5.1.6 on 2025-03-11 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_uuid_temp_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid_temp',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
