# Generated by Django 5.1.6 on 2025-03-11 14:38

import uuid
from django.db import migrations, models

def generate_uuid(apps, schema_editor):
    Product = apps.get_model('product', 'Product')
    for product in Product.objects.all():
        product.product_id = str(uuid.uuid4())
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_product_uuid_temp_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
